/* AUTO-GENERATED by scripts/build-blog.mjs. Do not edit by hand. */
export const RECENT_POSTS = [
  {
    "slug": "work-from-home-scams",
    "title": "Work-From-Home Scams: The Complete 2026 Guide",
    "description": "The complete 2026 guide to work-from-home scams — fake check scams, task/text scams, reshipping, MLMs, fake job listings, and impersonation. How to spot them, with one rule that catches most."
  },
  {
    "slug": "legit-work-from-home-company-reviews",
    "title": "Legit Work-From-Home Companies: Honest Reviews (2026)",
    "description": "Honest 2026 reviews of legit work-from-home companies and platforms — AI training, customer service, moderation, and transcription. Real pay, real catches, no hype, no affiliate links."
  },
  {
    "slug": "reshipping-package-forwarding-job-scam",
    "title": "The Reshipping Job Scam: Why \"Package Forwarding\" Work Is a Trap (2026)",
    "description": "Reshipping and \"package forwarding\" jobs are a common work-from-home scam in 2026. Here is how the trap works, why it is dangerous, the red flags, and what to do if you're caught in one."
  },
  {
    "slug": "is-remotasks-legit",
    "title": "Is Remotasks Legit in 2026? An Honest Review (Pay, Reviews, Red Flags)",
    "description": "Is Remotasks legit or a scam in 2026? An honest review of pay, the mixed reviews, how work availability varies by region, and the red flags to know before you sign up."
  },
  {
    "slug": "is-outlier-ai-legit",
    "title": "Is Outlier AI Legit in 2026? An Honest Review (Pay, Work, Red Flags)",
    "description": "Is Outlier AI legit or a scam in 2026? An honest review of pay rates, the kind of work, who earns the most, payment reliability, and the real red flags to know before you start."
  },
  {
    "slug": "is-alignerr-legit",
    "title": "Is Alignerr Legit in 2026? An Honest Review (Pay, Work, Red Flags)",
    "description": "Is Alignerr legit or a scam in 2026? An honest review of pay, the kind of work, payment reliability, and the red flags to know before you sign up."
  }
];
