/* AUTO-GENERATED by scripts/build-blog.mjs. Do not edit by hand. */
export const RECENT_POSTS = [
  {
    "slug": "work-from-home-jobs-for-people-with-disabilities",
    "title": "Work-From-Home Jobs for People With Disabilities (Real Options, 2026)",
    "description": "Honest guide to legitimate work-from-home jobs for people with disabilities in 2026. Flexible roles, realistic pay, free placement nonprofits, accommodations, and how to avoid the scams that target disabled workers."
  },
  {
    "slug": "remote-seasonal-holiday-jobs",
    "title": "Remote Seasonal & Holiday Jobs: When to Apply and What They Pay (2026)",
    "description": "Honest guide to remote seasonal and holiday work-from-home jobs in 2026. When to apply, what they pay, which companies hire, and how to avoid seasonal job scams."
  },
  {
    "slug": "remote-jobs-for-veterans",
    "title": "Remote Jobs for Veterans (Real, Well-Paid Options for 2026)",
    "description": "Honest guide to remote jobs for veterans in 2026. Veteran-friendly employers, roles that value military skills, realistic pay, free hiring programs, and the scams that target service members."
  },
  {
    "slug": "medical-coding-jobs-from-home-no-experience",
    "title": "Medical Coding Jobs From Home With No Experience (Honest 2026 Guide)",
    "description": "Honest guide to remote medical coding jobs with no experience in 2026. What certification you really need, realistic costs and pay, how long it takes, and how to avoid coding-school scams."
  },
  {
    "slug": "is-ttec-legit",
    "title": "Is TTEC Legit? An Honest 2026 Review (Work-From-Home Customer Service)",
    "description": "Honest 2026 review of TTEC work-from-home jobs. Is TTEC legit, what it really pays, the pros and cons from real employees, and who the role actually suits."
  },
  {
    "slug": "is-concentrix-legit",
    "title": "Is Concentrix Legit? An Honest 2026 Review (Work-From-Home Jobs)",
    "description": "Honest 2026 review of Concentrix work-from-home jobs. Is Concentrix legit, what it really pays, real employee pros and cons, monitoring, and how to avoid Concentrix impersonation scams."
  }
];
